### ISSUE TITLE
Works fine on my local server but not on github pages

### ISSUE THREAD

**Issue by techraiders** [tinacious/angular-easy-social-share#5]
![issue](https://cloud.githubusercontent.com/assets/19530178/18172398/d5476728-7082-11e6-891b-f93060c3ffe5.png)

See the screenshot, it produces error when deployed on gh-pages. Works fine on local node js http-server

**Comment by tinacious** [comment]
@techraiders you are committing your Node modules and therefore every dependency in it, which is understood as a Git repo. The error is because you are committing additional repos and haven't registered them as submodules. You should look into how to properly use Git submodules, use Bower, or use a build tool like Gulp or Grunt to build it into a separate file. It's actually a bad practice to commit your Node modules. You may find [this](http://stackoverflow.com/questions/17441904/git-submodules-in-gitmodules-not-initialized) useful if you choose to go down the submodules route. 

This is unrelated to my code and rather your implementation of it. I am closing this issue.
